<?php
	
	class SQL_harezad {
		
		/*
			Note:
			-----
			
			1. To pass a parameter value, write <PARAMx>. x = number starting 1.
		*/
		
		public static function sql($str_sqlID) {
			$ary_sql = array(
				"AllBuildingList" => "SELECT V.DESCRIPTION AS PTT_NAME,W.DESCRIPTION AS ZONE_NAME,X.ID AS BUILDING_ID,X.DESCRIPTION AS BUILD_NAME,X.TR_THRESHOLD AS INV_TARGET FROM AREA X INNER JOIN (AREA W INNER JOIN AREA V on W.PARENT_ID = V.ID) ON X.PARENT_ID = W.ID WHERE V.TYPE='PTT' AND X.DEPLOY_FLAG = 1 ORDER BY V.NAME,W.NAME,X.NAME",
				"AllPTT" => "SELECT * FROM AREA WHERE UPPER(TYPE) = 'PTT' ORDER BY DESCRIPTION",
				"ZoneByParentID" => "SELECT * FROM AREA WHERE UPPER(TYPE) = 'ZONE' AND PARENT_ID = <PARAM1>",
				"BuildingByParentID" => "SELECT * FROM AREA WHERE UPPER(TYPE) = 'BUILDING' AND PARENT_ID = <PARAM1>",
				"F_UNIFY_FULLFILMENT" => "SELECT * FROM TABLE(F_UNIFY_FULLFILMENT)",
				"Status_F_UNIFY_FULLFILMENT" => "SELECT DISTINCT ACTIVITY_TYPE FROM TABLE(F_UNIFY_FULLFILMENT) WHERE NOT ACTIVITY_TYPE IS NULL ORDER BY ACTIVITY_TYPE ASC"
			);
			return $ary_sql[$str_sqlID];
		}
	}
?>