<?php
	
	class SQL_UserMenu {
		
		/*	Note:
			-----
			1. To pass a parameter value, write <PARAMx>. x = number starting 1.
		*/
		
		public static function sql($str_sqlID) {
			$ary_sql = array(
				"SysUserInfo" => "SELECT U.STAFF_NO,U.NAME,U.ROLE_ID,(SELECT DESCRIPTION FROM USER_GROUP WHERE ROLE_ID = U.ROLE_ID AND ROWNUM = 1) AS GROUPNM FROM SYSTEM_USER U WHERE U.ID = <PARAM1>",
				"MenuList" => "SELECT * FROM MENU_LIST ORDER BY PARENTID,ORDINAL",
				"GroupMenu" => "SELECT MENU_LIST_ID FROM USER_GROUP_MENU_LIST WHERE ROLE_ID = <PARAM1>",
				"UserOVRMenu" => "SELECT * FROM USER_MENU_EXT WHERE CAST(STAFF_NO AS INTEGER) = <PARAM1>",
				"UserOvrwMenuXML" => "SELECT * FROM (SELECT MENU_LIST_ID,DESCRIPTION,LINK,PARENTID,ORDINAL FROM MENU_LIST WHERE OWNER = <PARAM2> AND PARENTID > 0 AND MENU_LIST_ID IN (SELECT G.MENU_LIST_ID FROM SYSTEM_USER U INNER JOIN USER_GROUP_MENU_LIST G ON U.ROLE_ID = G.ROLE_ID WHERE U.ID = <PARAM1> AND NOT G.MENU_LIST_ID IN (SELECT MENU_LIST_ID FROM USER_MENU_EXT WHERE ACCESS_RIGHT = '0' AND CAST(STAFF_NO AS INTEGER) = U.ID) UNION SELECT MENU_LIST_ID FROM USER_MENU_EXT WHERE ACCESS_RIGHT = '1' AND CAST(STAFF_NO AS INTEGER) = <PARAM1>) UNION SELECT MENU_LIST_ID,DESCRIPTION,LINK,PARENTID,ORDINAL FROM MENU_LIST WHERE PARENTID = 0) X ORDER BY PARENTID,ORDINAL",
				"MenuAccessInfo" => "SELECT * FROM (SELECT DISTINCT U.ROLE_ID AS ID,G.DESCRIPTION AS NAME,'-' AS CAT,U.MENU_LIST_ID AS MENU_ID FROM USER_GROUP_MENU_LIST U INNER JOIN USER_GROUP G ON U.ROLE_ID = G.ROLE_ID UNION SELECT S.ID AS ID,(S.STAFF_NO || '-' || S.NAME) AS NAME,X.ACCESS_RIGHT AS CAT,X.MENU_LIST_ID AS MENU_ID FROM SYSTEM_USER S INNER JOIN USER_MENU_EXT X ON S.ID = CAST(X.STAFF_NO AS INTEGER))Z WHERE Z.MENU_ID = <PARAM1>"
			);
			return $ary_sql[$str_sqlID];
		}
	}
?>